// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmlHV7HOsK52IZTNRNKqxofUh2CDgRVYw',
    appId: '1:160945755077:web:ce4d9651961de7ac2cb1ac',
    messagingSenderId: '160945755077',
    projectId: 'blood-donation-afef5',
    authDomain: 'blood-donation-afef5.firebaseapp.com',
    storageBucket: 'blood-donation-afef5.firebasestorage.app',
    measurementId: 'G-GY3GK19D4N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCt7UtcZuF_v8a1WTI17IsfrbEZjew1V38',
    appId: '1:160945755077:android:a973b4631abe76bb2cb1ac',
    messagingSenderId: '160945755077',
    projectId: 'blood-donation-afef5',
    storageBucket: 'blood-donation-afef5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbCbQAZ3GZNxP27CTk0sQ0iYfopaRPfH8',
    appId: '1:160945755077:ios:a14377ec37316baf2cb1ac',
    messagingSenderId: '160945755077',
    projectId: 'blood-donation-afef5',
    storageBucket: 'blood-donation-afef5.firebasestorage.app',
    iosBundleId: 'com.example.blooddonation',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbCbQAZ3GZNxP27CTk0sQ0iYfopaRPfH8',
    appId: '1:160945755077:ios:a14377ec37316baf2cb1ac',
    messagingSenderId: '160945755077',
    projectId: 'blood-donation-afef5',
    storageBucket: 'blood-donation-afef5.firebasestorage.app',
    iosBundleId: 'com.example.blooddonation',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBmlHV7HOsK52IZTNRNKqxofUh2CDgRVYw',
    appId: '1:160945755077:web:e880bc9aaa85df362cb1ac',
    messagingSenderId: '160945755077',
    projectId: 'blood-donation-afef5',
    authDomain: 'blood-donation-afef5.firebaseapp.com',
    storageBucket: 'blood-donation-afef5.firebasestorage.app',
    measurementId: 'G-RMX0NMTJCM',
  );
}
